2024-07-17 15:32:58,097 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Current SDK version is 0.17.4
2024-07-17 15:32:58,099 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Configure stats pid to 73741
2024-07-17 15:32:58,100 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Loading settings from /home/vscode/.config/wandb/settings
2024-07-17 15:32:58,101 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Loading settings from /workspaces/speml24_2/code/wandb/settings
2024-07-17 15:32:58,103 WARNING MainThread:73741 [wandb_setup.py:_flush():76] Unknown environment variable: WANDB_KEY
2024-07-17 15:32:58,105 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-17 15:32:58,106 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-07-17 15:32:58,108 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-07-17 15:32:58,109 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-07-17 15:32:58,111 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-17 15:32:58,112 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-07-17 15:32:58,113 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-07-17 15:32:58,114 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-17 15:32:58,115 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-07-17 15:32:58,116 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-07-17 15:32:58,118 INFO    MainThread:73741 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-17 15:32:58,119 ERROR   MainThread:73741 [wandb_setup.py:_flush():78] error in wandb.init()
Traceback (most recent call last):
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-8baa351479fb>", line 19, in <module>
    start_training(num_workers=NUM_WORKERS)
  File "<ipython-input-9-8baa351479fb>", line 2, in start_training
    model = SimpleCNN().to(device)
  File "<ipython-input-6-88ece903a54e>", line 8, in __init__
    self.logger = WandBLogger(model=self)
  File "<ipython-input-8-3ce7204b2c53>", line 11, in __init__
    wandb.init(entity="wojo-michaluk",
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1195, in init
    wandb._sentry.reraise(e)
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1180, in init
    wi.setup(kwargs)
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 316, in setup
    settings._apply_init(kwargs)
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1877, in _apply_init
    self.update(init_settings, source=Source.INIT)
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1506, in update
    self.__dict__[key].update(settings.pop(key), source=source)
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 598, in update
    self._value = self._validate(self._preprocess(value))
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 568, in _validate
    if not v(value):
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1019, in _validate_project
    raise UsageError(
wandb.errors.UsageError: Invalid project name 'speml/federated_learning/<run_id>': cannot contain characters '/,\\,#,?,%,:', found '/'
2024-07-17 15:32:58,121 ERROR   MainThread:73741 [wandb_setup.py:_flush():78] error in wandb.init()
Traceback (most recent call last):
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-8baa351479fb>", line 19, in <module>
    start_training(num_workers=NUM_WORKERS)
  File "<ipython-input-11-8baa351479fb>", line 2, in start_training
    model = SimpleCNN().to(device)
  File "<ipython-input-6-88ece903a54e>", line 8, in __init__
    self.logger = WandBLogger(model=self)
  File "<ipython-input-10-6eb880ae9db3>", line 11, in __init__
    wandb.init(entity="wojo-michaluk",
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1195, in init
    wandb._sentry.reraise(e)
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1180, in init
    wi.setup(kwargs)
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 316, in setup
    settings._apply_init(kwargs)
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1877, in _apply_init
    self.update(init_settings, source=Source.INIT)
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1506, in update
    self.__dict__[key].update(settings.pop(key), source=source)
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 598, in update
    self._value = self._validate(self._preprocess(value))
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 568, in _validate
    if not v(value):
  File "/opt/conda/envs/speml24_2/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1019, in _validate_project
    raise UsageError(
wandb.errors.UsageError: Invalid project name 'speml/federated_learning': cannot contain characters '/,\\,#,?,%,:', found '/'
2024-07-17 15:32:58,123 INFO    MainThread:73741 [wandb_init.py:_log_setup():529] Logging user logs to /workspaces/speml24_2/code/wandb/run-20240717_153258-ke336qa1/logs/debug.log
2024-07-17 15:32:58,125 INFO    MainThread:73741 [wandb_init.py:_log_setup():530] Logging internal logs to /workspaces/speml24_2/code/wandb/run-20240717_153258-ke336qa1/logs/debug-internal.log
2024-07-17 15:32:58,126 INFO    MainThread:73741 [wandb_init.py:init():569] calling init triggers
2024-07-17 15:32:58,128 INFO    MainThread:73741 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-07-17 15:32:58,129 INFO    MainThread:73741 [wandb_init.py:init():594] re-initializing run, found existing run on stack: 51ezisij
2024-07-17 15:32:58,133 INFO    MainThread:73741 [wandb_run.py:_finish():2109] finishing run wojo-michaluk/federated_learning/51ezisij
2024-07-17 15:32:58,134 INFO    MainThread:73741 [jupyter.py:save_history():444] not saving jupyter history
2024-07-17 15:32:58,135 INFO    MainThread:73741 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-07-17 15:32:58,136 INFO    MainThread:73741 [wandb_init.py:_jupyter_teardown():457] cleaning up jupyter logic
2024-07-17 15:32:58,137 INFO    MainThread:73741 [wandb_run.py:_atexit_cleanup():2349] got exitcode: 0
2024-07-17 15:32:58,139 INFO    MainThread:73741 [wandb_run.py:_restore():2332] restore
2024-07-17 15:32:58,140 INFO    MainThread:73741 [wandb_run.py:_restore():2338] restore done
2024-07-17 15:33:03,728 INFO    MainThread:73741 [wandb_run.py:_footer_history_summary_info():3991] rendering history
2024-07-17 15:33:03,729 INFO    MainThread:73741 [wandb_run.py:_footer_history_summary_info():4023] rendering summary
2024-07-17 15:33:03,745 INFO    MainThread:73741 [wandb_run.py:_footer_sync_info():3950] logging synced files
2024-07-17 15:33:03,800 INFO    MainThread:73741 [wandb_init.py:init():619] starting backend
2024-07-17 15:33:03,801 INFO    MainThread:73741 [wandb_init.py:init():623] setting up manager
2024-07-17 15:33:03,818 INFO    MainThread:73741 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-07-17 15:33:03,819 INFO    MainThread:73741 [wandb_init.py:init():631] backend started and connected
2024-07-17 15:33:03,853 INFO    MainThread:73741 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-07-17 15:33:03,853 INFO    MainThread:73741 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-07-17 15:33:03,854 INFO    MainThread:73741 [wandb_init.py:init():720] updated telemetry
2024-07-17 15:33:04,036 INFO    MainThread:73741 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-17 15:33:05,511 INFO    MainThread:73741 [wandb_run.py:_on_init():2402] communicating current version
2024-07-17 15:33:05,585 INFO    MainThread:73741 [wandb_run.py:_on_init():2411] got version response 
2024-07-17 15:33:05,586 INFO    MainThread:73741 [wandb_init.py:init():804] starting run threads in backend
2024-07-17 15:33:08,643 INFO    MainThread:73741 [wandb_run.py:_console_start():2380] atexit reg
2024-07-17 15:33:08,643 INFO    MainThread:73741 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2024-07-17 15:33:08,644 INFO    MainThread:73741 [wandb_run.py:_redirect():2300] Wrapping output streams.
2024-07-17 15:33:08,644 INFO    MainThread:73741 [wandb_run.py:_redirect():2325] Redirects installed.
2024-07-17 15:33:08,645 INFO    MainThread:73741 [wandb_init.py:init():847] run started, returning control to user process
2024-07-17 15:33:08,646 INFO    MainThread:73741 [wandb_watch.py:watch():51] Watching
